name: Clang-Tidy CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang-tidy libsfml-dev libncurses5-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Run clang-tidy
      run: |
        find ${{github.workspace}}/src -name "*.cpp" -o -name "*.h" | grep -v "/tests/" | \
        xargs clang-tidy -p ${{github.workspace}}/build

    - name: Check for clang-tidy errors
      if: ${{ failure() }}
      run: echo "Clang-tidy checks failed. Please fix the issues and try again." 